---
- name: Create VM shell on standalone ESXi
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware
    
  tasks:
    - name: Create empty VM shell
      vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ vm_name }}"
        folder: "{{ vm_folder }}"
        datacenter: "{{ vm_datacenter }}"
        state: present
        guest_id: "{{ vm_guest_id }}"
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpu }}"
          scsi: paravirtual
        disk:
          - size_gb: 100
            type: thin
            datastore: "Datastore-SSD-01"
        networks:
          - name: "{{ vm_network }}"
            start_connected: yes
            connected: yes
            device_type: vmxnet3
        wait_for_ip_address: no
      delegate_to: localhost
