- name: Generate Hostnames and Run PowerShell Script on Remote Windows Server
  hosts: 10.0.1.1
  gather_facts: no

  tasks:
    - name: Generate hostname for each VM
      include_tasks: Generate-Hostname.yaml
      vars:
        prefix: "ABLAB"
        role_code: "{{ role_code }}"
        index_file: "/var/lib/awx/projects/common/hostname_index.yml"
      loop: "{{ vm_list }}"
      loop_control:
        loop_var: vm_item
      register: generated_hostnames

    - name: Debug generated hostnames
      debug:
        msg: "Generated hostname: {{ item.msg }}"
      loop: "{{ generated_hostnames.results }}"

    - name: Run PowerShell script for each VM
      ansible.windows.win_shell: |
        powershell.exe -File "C:\Scripts\Create_VM_On_ESXi.ps1" -Hostname "{{ item.msg }}" -Subnet "{{ item.item.subnet }}"
      args:
        executable: powershell.exe
      loop: "{{ generated_hostnames.results }}"
      register: script_output

    - name: Display script output for each VM
      debug:
        msg: "Output for {{ item.item.item.subnet }}: {{ item.stdout }}"
      loop: "{{ script_output.results }}"