# This task file generates and updates hostnames like ABLABW001 dynamically.

- name: Load current index file
  slurp:
    src: "{{ index_file }}"
  register: index_file_raw
  ignore_errors: true

- name: Parse index data or initialize if file is missing
  set_fact:
    index_data: "{{ {} if index_file_raw.failed else index_file_raw.content | b64decode | from_yaml }}"

- name: Calculate new index and hostname
  set_fact:
    full_key: "{{ prefix }}{{ role_code }}"
    current_index: "{{ index_data[full_key] | default(0) }}"
    new_index: "{{ current_index + 1 }}"
    new_hostname: "{{ full_key }}{{ '%03d' | format(new_index) }}"

- name: Show the generated hostname
  debug:
    msg: "✅ New hostname: {{ new_hostname }}"

- name: Update index with the new value
  set_fact:
    updated_index_data: "{{ index_data | combine({ full_key: new_index }) }}"

- name: Write updated index back to the file
  copy:
    dest: "{{ index_file }}"
    content: "{{ updated_index_data | to_nice_yaml }}"