# This task file generates and updates hostnames like ABLABW001 dynamically using a MySQL table.

- name: Retrieve the current index from MySQL
  community.mysql.mysql_query:
    login_host: "192.168.1.58"
    login_user: "mysqluser"
    login_password: "{{ mysql_password }}"
    login_database: "ablab_db"
    query: "SELECT `index` FROM tblhostname_index WHERE role = '{{ role_code }}';"
  register: mysql_index_result

- name: Initialize index if no entry exists
  community.mysql.mysql_query:
    login_host: "192.168.1.58"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
    login_database: "ablab_db"
    query: "INSERT INTO tblhostname_index (role, `index`) VALUES ('{{ role_code }}', 0);"
  when: mysql_index_result.results | length == 0

- name: Retrieve the updated index after initialization (if needed)
  community.mysql.mysql_query:
    login_host: "192.168.1.58"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
    login_database: "ablab_db"
    query: "SELECT `index` FROM tblhostname_index WHERE role = '{{ role_code }}';"
  register: mysql_index_result
  when: mysql_index_result.results | length == 0

- name: Increment the index in MySQL
  community.mysql.mysql_query:
    login_host: "192.168.1.58"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
    login_database: "ablab_db"
    query: "UPDATE tblhostname_index SET `index` = `index` + 1 WHERE role = '{{ role_code }}';"

- name: Retrieve the new index value from MySQL
  community.mysql.mysql_query:
    login_host: "192.168.1.58"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
    login_database: "ablab_db"
    query: "SELECT `index` FROM tblhostname_index WHERE role = '{{ role_code }}';"
  register: mysql_new_index_result

- name: Calculate the new hostname
  set_fact:
    new_index: "{{ mysql_new_index_result.results[0].index }}"
    new_hostname: "{{ prefix }}{{ role_code }}{{ '%03d' | format(new_index) }}"

- name: Show the generated hostname
  debug:
    msg: "✅ New hostname: {{ new_hostname }}"