---
- name: Deploy VMs from OVF on ESXi
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Connect to ESXi
      vmware.vmware.esxi_connection:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no

    - name: Deploy VMs from OVF
      community.vmware.vmware_deploy_ovf:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        datastore: "{{ datastore_name }}"
        cluster: ""
        vm_folder: ""
        ovf: "{{ ovf_path }}"
        name: "{{ item.hostname }}"
        disk_provisioning: "thin"
      loop: "{{ vm_list }}"
      register: deployed_vms

    - name: Configure advanced settings for each VM
      community.vmware.vmware_vm_shell:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        vm_name: "{{ item.hostname }}"
        commands:
          - "guestinfo.labvm.hostname={{ item.hostname }}"
          - "guestinfo.labvm.ipaddr={{ item.ip }}"
          - "guestinfo.labvm.gateway={{ item.gateway }}"
          - "guestinfo.labvm.subnet={{ item.subnet }}"
          - "guestinfo.labvm.dns={{ item.dns }}"
      loop: "{{ vm_list }}"

    - name: Start the VMs
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ item.hostname }}"
        state: powered_on
      loop: "{{ vm_list }}"